config/routes.rb
Rails.application.routes.draw do
  get 'people/update'
  get 'people/delete'
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @people = Person.find(params[:id])
  end

  def new
    @people = Person.new
  end

  def update
    @people = Person.find(:id)
  end

  # def create
  #   @people = Person.new(person_params)
 
  #   if @people.save
  #     redirect_to people_path
  #   else
  #     render :new
  #   end

  # end

  # def update
  #   @people = Person.find(params[:id])
  #   @people.update_attribute(:age, "")
  # end

  # private 
  # def person_params
  #   params.require(:).permit(:name, :age, :hair_color)
  # end

 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/delete.html.erb
<h1>People#delete</h1>
<p>Find me in app/views/people/delete.html.erb</p>

app/views/people/index.html.erb
<h1>People App</h1>
<p><%= link_to 'New Page', new_person_path %></p>
<p><%= link_to 'Update', people_update_path %></p>

<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <%= link_to 'Show Page', person_path(person) %>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<%= form_for @people do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_area :eye_color %>

  <%= f.label :gender %>
  <%= f.text_area :gender %>

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1> Name: <%= @people.name %></h1>
<h4> Age: <%= @people.age %></h4>
<h4> Hair Color: <%= @people.hair_color %></h4>
<h4> Eye Color: <%= @people.eye_color %></h4>
<h4> Gender: <%= @people.gender %></h4>
<h4> Alive? <%= @people.alive %></h4>
<%= link_to 'Back', people_path %>

app/views/people/update.html.erb
<h1>Update Persons Information</h1>

<%= form_for @people do |f| %>
  <%= f.label :name %>
  <%= f.update :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_area :eye_color %>

  <%= f.label :gender %>
  <%= f.text_area :gender %>

  <%= f.submit %>
<% end %>